name: Ubuntu Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake libpcl-dev liblz4-dev libzstd-dev libgtest-dev

      - name: Configure
        run: cmake cloudini_lib -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build
        run: make -j$(nproc)

      - name: Run tests
        run: ctest --output-on-failure
